# uv tool install harlequin --with harlequin-mysql
# https://harlequin.sh/docs/config-file/creating-config
default_profile = "ysoftman"

# harlequin --keys 로 편집 가능
[[keymaps.my_custom_keys]]
keys = "ctrl+q,f12"
action = "quit"
key_display = "quit"

[[keymaps.my_custom_keys]]
keys = "f1"
action = "help"

[[keymaps.my_custom_keys]]
keys = "tab"
action = "focus_next"

[[keymaps.my_custom_keys]]
keys = "shift+tab"
action = "focus_previous"

[[keymaps.my_custom_keys]]
keys = "f2"
action = "focus_query_editor"

[[keymaps.my_custom_keys]]
keys = "f5"
action = "focus_results_viewer"

[[keymaps.my_custom_keys]]
keys = "f6"
action = "focus_data_catalog"

[[keymaps.my_custom_keys]]
keys = "ctrl+b,f9"
action = "toggle_sidebar"

[[keymaps.my_custom_keys]]
keys = "f10"
action = "toggle_full_screen"

[[keymaps.my_custom_keys]]
keys = "f12"
action = "show_debug_info"

[[keymaps.my_custom_keys]]
keys = "f8"
action = "show_query_history"

[[keymaps.my_custom_keys]]
keys = "ctrl+e"
action = "show_data_exporter"

[[keymaps.my_custom_keys]]
keys = "ctrl+r"
action = "refresh_catalog"

[[keymaps.my_custom_keys]]
keys = "ctrl+n"
action = "code_editor.new_buffer"

[[keymaps.my_custom_keys]]
keys = "ctrl+w"
action = "code_editor.close_buffer"

[[keymaps.my_custom_keys]]
keys = "ctrl+k"
action = "code_editor.next_buffer"

[[keymaps.my_custom_keys]]
keys = "ctrl+enter,ctrl+j"
action = "code_editor.run_query"
key_display = "^⏎ or ^j"

[[keymaps.my_custom_keys]]
keys = "f4"
action = "code_editor.format_buffer"

[[keymaps.my_custom_keys]]
keys = "ctrl+s"
action = "code_editor.save_buffer"

[[keymaps.my_custom_keys]]
keys = "ctrl+o"
action = "code_editor.load_buffer"

[[keymaps.my_custom_keys]]
keys = "ctrl+f"
action = "code_editor.find"

[[keymaps.my_custom_keys]]
keys = "f3"
action = "code_editor.find_next"

[[keymaps.my_custom_keys]]
keys = "ctrl+g"
action = "code_editor.goto_line"

[[keymaps.my_custom_keys]]
keys = "up"
action = "code_editor.cursor_up"

[[keymaps.my_custom_keys]]
keys = "down"
action = "code_editor.cursor_down"

[[keymaps.my_custom_keys]]
keys = "left"
action = "code_editor.cursor_left"

[[keymaps.my_custom_keys]]
keys = "right"
action = "code_editor.cursor_right"

[[keymaps.my_custom_keys]]
keys = "ctrl+left"
action = "code_editor.cursor_word_left"

[[keymaps.my_custom_keys]]
keys = "ctrl+right"
action = "code_editor.cursor_word_right"

[[keymaps.my_custom_keys]]
keys = "home"
action = "code_editor.cursor_line_start"

[[keymaps.my_custom_keys]]
keys = "end"
action = "code_editor.cursor_line_end"

[[keymaps.my_custom_keys]]
keys = "ctrl+home"
action = "code_editor.cursor_doc_start"

[[keymaps.my_custom_keys]]
keys = "ctrl+end"
action = "code_editor.cursor_doc_end"

[[keymaps.my_custom_keys]]
keys = "pageup"
action = "code_editor.cursor_page_up"

[[keymaps.my_custom_keys]]
keys = "pagedown"
action = "code_editor.cursor_page_down"

[[keymaps.my_custom_keys]]
keys = "shift+up"
action = "code_editor.select_up"

[[keymaps.my_custom_keys]]
keys = "shift+down"
action = "code_editor.select_down"

[[keymaps.my_custom_keys]]
keys = "shift+left"
action = "code_editor.select_left"

[[keymaps.my_custom_keys]]
keys = "shift+right"
action = "code_editor.select_right"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+left"
action = "code_editor.select_word_left"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+right"
action = "code_editor.select_word_right"

[[keymaps.my_custom_keys]]
keys = "shift+home"
action = "code_editor.select_line_start"

[[keymaps.my_custom_keys]]
keys = "shift+end"
action = "code_editor.select_line_end"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+home"
action = "code_editor.select_doc_start"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+end"
action = "code_editor.select_doc_end"

[[keymaps.my_custom_keys]]
keys = "ctrl+a"
action = "code_editor.select_all"

[[keymaps.my_custom_keys]]
keys = "ctrl+up"
action = "code_editor.scroll_up_one"

[[keymaps.my_custom_keys]]
keys = "ctrl+down"
action = "code_editor.scroll_down_one"

[[keymaps.my_custom_keys]]
keys = "ctrl+underscore"
action = "code_editor.toggle_comment"

[[keymaps.my_custom_keys]]
keys = "ctrl+x"
action = "code_editor.cut"

[[keymaps.my_custom_keys]]
keys = "ctrl+c"
action = "code_editor.copy"

[[keymaps.my_custom_keys]]
keys = "ctrl+u,ctrl+v,shift+insert"
action = "code_editor.paste"

[[keymaps.my_custom_keys]]
keys = "ctrl+z"
action = "code_editor.undo"

[[keymaps.my_custom_keys]]
keys = "ctrl+y"
action = "code_editor.redo"

[[keymaps.my_custom_keys]]
keys = "backspace"
action = "code_editor.delete_left"

[[keymaps.my_custom_keys]]
keys = "delete"
action = "code_editor.delete_right"

[[keymaps.my_custom_keys]]
keys = "shift+delete"
action = "code_editor.delete_line"

[[keymaps.my_custom_keys]]
keys = "j"
action = "data_catalog.previous_tab"

[[keymaps.my_custom_keys]]
keys = "k"
action = "data_catalog.next_tab"

[[keymaps.my_custom_keys]]
keys = "ctrl+enter,ctrl+j"
action = "data_catalog.insert_name"
key_display = "^⏎ or ^j"

[[keymaps.my_custom_keys]]
keys = "ctrl+c"
action = "data_catalog.copy_name"

[[keymaps.my_custom_keys]]
keys = "enter"
action = "data_catalog.select_cursor"

[[keymaps.my_custom_keys]]
keys = "space"
action = "data_catalog.toggle_node"

[[keymaps.my_custom_keys]]
keys = "up"
action = "data_catalog.cursor_up"

[[keymaps.my_custom_keys]]
keys = "down"
action = "data_catalog.cursor_down"

[[keymaps.my_custom_keys]]
keys = "full_stop"
action = "data_catalog.show_context_menu"

[[keymaps.my_custom_keys]]
keys = "escape"
action = "data_catalog.hide_context_menu"

[[keymaps.my_custom_keys]]
keys = "j"
action = "results_viewer.previous_tab"

[[keymaps.my_custom_keys]]
keys = "k"
action = "results_viewer.next_tab"

[[keymaps.my_custom_keys]]
keys = "ctrl+c"
action = "results_viewer.copy_selection"

[[keymaps.my_custom_keys]]
keys = "enter"
action = "results_viewer.select_cursor"

[[keymaps.my_custom_keys]]
keys = "k,up"
action = "results_viewer.cursor_up"
key_display = "⬆/k"

[[keymaps.my_custom_keys]]
keys = "down,j"
action = "results_viewer.cursor_down"
key_display = "⬇/j"

[[keymaps.my_custom_keys]]
keys = "h,left"
action = "results_viewer.cursor_left"
key_display = "⬅/h"

[[keymaps.my_custom_keys]]
keys = "l,right"
action = "results_viewer.cursor_right"
key_display = "➡/l"

[[keymaps.my_custom_keys]]
keys = "ctrl+left"
action = "results_viewer.cursor_row_start"

[[keymaps.my_custom_keys]]
keys = "ctrl+right"
action = "results_viewer.cursor_row_end"

[[keymaps.my_custom_keys]]
keys = "ctrl+up,home"
action = "results_viewer.cursor_column_start"

[[keymaps.my_custom_keys]]
keys = "ctrl+down,end"
action = "results_viewer.cursor_column_end"

[[keymaps.my_custom_keys]]
keys = "tab"
action = "results_viewer.cursor_next_cell"

[[keymaps.my_custom_keys]]
keys = "shift+tab"
action = "results_viewer.cursor_previous_cell"

[[keymaps.my_custom_keys]]
keys = "pageup"
action = "results_viewer.cursor_page_up"

[[keymaps.my_custom_keys]]
keys = "pagedown"
action = "results_viewer.cursor_page_down"

[[keymaps.my_custom_keys]]
keys = "ctrl+home"
action = "results_viewer.cursor_table_start"

[[keymaps.my_custom_keys]]
keys = "ctrl+end"
action = "results_viewer.cursor_table_end"

[[keymaps.my_custom_keys]]
keys = "shift+up"
action = "results_viewer.select_up"

[[keymaps.my_custom_keys]]
keys = "shift+down"
action = "results_viewer.select_down"

[[keymaps.my_custom_keys]]
keys = "shift+left"
action = "results_viewer.select_left"

[[keymaps.my_custom_keys]]
keys = "shift+right"
action = "results_viewer.select_right"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+left"
action = "results_viewer.select_row_start"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+right"
action = "results_viewer.select_row_end"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+up,shift+home"
action = "results_viewer.select_column_start"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+down,shift+end"
action = "results_viewer.select_column_end"

[[keymaps.my_custom_keys]]
keys = "shift+pageup"
action = "results_viewer.select_page_up"

[[keymaps.my_custom_keys]]
keys = "shift+pagedown"
action = "results_viewer.select_page_down"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+home"
action = "results_viewer.select_table_start"

[[keymaps.my_custom_keys]]
keys = "ctrl+shift+end"
action = "results_viewer.select_table_end"

[[keymaps.my_custom_keys]]
keys = "ctrl+a"
action = "results_viewer.select_all"

[[keymaps.my_custom_keys]]
keys = "enter"
action = "history_screen.select_query"

[[keymaps.my_custom_keys]]
keys = "escape"
action = "history_screen.cancel"

[profiles.ysoftman]
adapter = "mysql"
theme = "dracula"
limit = 100_000
host = ""                                  # --host, -h 옵션으로 실행시 입력받도록 하자
port = "3306"
user = ""                                  # --user 옵션으로 실행시 입력받도록 하자
password = ""                              # --password 옵션으로 실행시 입력받도록 하자
database = ""                              # --database, -d, -db 옵션으로 실행시 입력받도록 하자
connection_timeout = "10"
keymap_name = ["vscode", "my_custom_keys"]
