version = 3
final_space = true

[upgrade]
source = 'cdn'
interval = '168h'
auto = false
notice = false

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
leading_diamond = ''
template = '{{ .Icon }} {{ .HostName }} '
foreground = '#00c983'
background = '#003543'
type = 'os'
style = 'diamond'

[[blocks.segments]]
template = '  {{.Context}}{{if .Namespace}}:{{.Namespace}}{{end}}'
foreground = '#000000'
powerline_symbol = ''
# background = '#ebcc34'
background = "#f9e2af"
type = 'kubectl'
style = 'powerline'

[blocks.segments.properties]
[blocks.segments.properties.context_aliases]
'arn:aws:eks:eu-west-1:1234567890:cluster/posh' = 'posh'

[[blocks.segments]]
template = ' <#000000> ➜</> {{ .Path }} '
foreground = '#000000'
powerline_symbol = ''
# background = '#DA627D'
background = "#f38ba8"
type = 'path'
style = 'powerline'

[blocks.segments.properties]
folder_icon = ''
folder_separator_icon = '\'
home_icon = ''
style = 'full'

[[blocks.segments]]
template = ' ({{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}) '
foreground = '#000000'
powerline_symbol = ''
# background = '#FCA17D'
background = "#fab387"
type = 'git'
style = 'powerline'

[blocks.segments.properties]
branch_icon = ' <#000000> </>'
fetch_stash_count = true
fetch_status = false
fetch_upstream_icon = true

[[blocks.segments]]
template = '  {{ .Full }} '
foreground = '#100e23'
powerline_symbol = ''
background = '#906cff'
type = 'python'
style = 'powerline'

[[blocks.segments]]
template = ' <#000000>󰎙</> {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '
foreground = '#000000'
powerline_symbol = ''
# background = '#76b367'
background = "#a6e3a1"
type = 'node'
style = 'powerline'

[[blocks.segments]]
template = "  {{ .Full }} "
style = "powerline"
powerline_symbol = ""
foreground = '#000000'
background = "#81a1c1"
type = "react"

[[blocks.segments]]
template = " <#ffffff></> {{ .Full }} "
type = "bun"
foreground = '#000000'
background = "#3C82F6"
powerline_symbol = ''
style = 'powerline'
# style = "plain"

[[blocks.segments]]
template = '  {{ .Full }} '
foreground = '#000000'
powerline_symbol = ''
background = '#7FD5EA'
style = 'powerline'
type = 'go'

[[blocks.segments]]
template = '  {{ .Full }} '
foreground = '#193549'
powerline_symbol = ''
background = '#99908a'
style = 'powerline'
type = 'rust'

[[blocks.segments]]
template = '  {{ .CurrentDate | date .Format }} '
foreground = '#000000'
powerline_symbol = ''
# background = '#33658A'
background = "#89b4fa"
type = 'time'
style = 'powerline'

[blocks.segments.properties]
time_format = '3:04 PM'

[[blocks.segments]]
template = ' <#000000>󰔟</> {{ .FormattedMs }} '
foreground = '#000000'
powerline_symbol = ''
# background = '#83769c'
background = "#cba6f7"
type = 'executiontime'
style = 'powerline'

[blocks.segments.properties]
always_enabled = true

[[blocks.segments]]
trailing_diamond = ''
template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
foreground = '#ffffff'
powerline_symbol = ''
# background = '#2e9599'
background = "#81c8be"
type = 'status'
style = 'diamond'
background_templates = ['{{ if gt .Code 0 }}red{{ end }}']

[blocks.segments.properties]
always_enabled = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

# root user 일때
[[blocks.segments]]
template = ' '
foreground = '#cd5e42'
type = 'root'
style = 'plain'

[[blocks.segments]]
template = ' <#45F1C2><b>⚡</b></><b>{{ .UserName }}</b> <#26C6DA>❯</><#45F1C2>❯</>'
foreground = '#CD4277'
type = 'text'
style = 'plain'
